name: ChrisBurrows
favicon: null
layout_spectrum: 0.16686002747155726
typography_spectrum: 0.113506167428568
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9383426420390606
  lightness: 0.3044566856697202
  saturation: 0.35513424640521407
  rhythmicContrast: 0.4312294733244926
purpose: []
